apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcare-hospital-ingress
  labels:
    app: cloudcare-hospital
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: cloudcare-hospital.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudcare-hospital-frontend-service
            port:
              number: 80
